[Settings]
;lcs or vcs
Mode = vcs

; alpha options
HUDAlpha =200
RadarMapAlpha=140
BlipsAlpha=180

; highlight keys
HighlightAreaVehicleNames = 0x54  ; T key

; radar keys
ZoomOut=0x54   ; T key
ExpandedRadar=0x58  ; X key (toggle between regular and expanded)

; removes the zeros from cash
MoneyPadZeros=1

; enables crosshair lock-on red color
CrosshairRedLockOn=1


[Colors]
; outline frame
OutlineR=255
OutlineG=255
OutlineB=255

; health
HealthR=255
HealthG=255
HealthB=255

; plus health
PlusHealthR=255
PlusHealthG=255
PlusHealthB=255

; armor
ArmorR=255
ArmorG=255
ArmorB=255

;plus armor
PlusArmorR=255
PlusArmorG=255
PlusArmorB=255

; breath (light blue)
BreathR=0
BreathG=100
BreathB=255

; breath underlay (dark blue)
BreathBgR=0
BreathBgG=20
BreathBgB=60

; stats tab bar
StatsR=255
StatsG=255
StatsB=255

; progress bar
ProgressBarR=255
ProgressBarG=255
ProgressBarB=255

; loading bar
LoadingBarR=255
LoadingBarG=255
LoadingBarB=255

; messages stats bar
MessagesStatsBarR=255
MessagesStatsBarG=255
MessagesStatsBarB=255

; color while scrolling through radio stations (dark blue)
ColorNormal_R=30
ColorNormal_G=60
ColorNormal_B=140
 
; color when locked onto a radio station (light blue)
ColorActive_R=100
ColorActive_G=180
ColorActive_B=255